### ISSUE TITLE
Configurables are exported with a 0 value price since version 5.2.0 and more specifically #11

### ISSUE THREAD

**Issue by Beagon** [EmicoEcommerce/Magento2TweakwiseExport#17]
Issue Brief
--
Configurables are exported with a 0 value price since version 5.2.0 and more specifically https://github.com/EmicoEcommerce/Magento2TweakwiseExport/pull/11
Environment
--
- [x] PHP Version: 8.1
- [x] Magento Version: 2.4.6-p1
- [x] Magento Enterprise: No
- [x] Tweakwise Export Version: 5.4.0
- [x] Magento Deploy Mode: production
- [x] Third party modules: Nothing that interferes.

Steps to reproduce
--
1. Install Magento from `master` branch.
2. Create configurable with multiple simples. Where the configurable price should be 0 and the childrens price should be a positive value. E.G €75
3. Export configurable product with multiple children and 2 configurable attributes to Tweakwise.
4. Check if there is a zero value in price.

Actual result
--
```
        <item>
            <id>123456</id>
            <name><![CDATA[Sample Product]]></name>
            <price>75</price>
            ...
            <attributes>
                <attribute datatype="numeric">
                    <name><![CDATA[price]]></name>
                    <value>0</value>
                </attribute>
                <attribute datatype="numeric">
                    <name><![CDATA[price]]></name>
                    <value>75</value>
                </attribute>
            </attributes>
            ...
        </item>
```
Expected result
--
```
        <item>
            <id>123456</id>
            <name><![CDATA[Sample Product]]></name>
            <price>75</price>
            ...
            <attributes>
                <attribute datatype="numeric">
                    <name><![CDATA[price]]></name>
                    <value>75</value>
                </attribute>
            </attributes>
            ...
        </item>
```

**Comment by ahuininga-orisha** [comment]
@Beagon Thx for the pull request. 

I'm not sure if this is the right place for the fix. What happens if you have an configurable with children with only 0 prices. Does the price still gets exported?

**Comment by Beagon** [comment]
This will only affect the addition of the Configurable. If there is a child with 0 prices underneath it it will be picked up by the ExportEntityChild class.

This is also what caused the issue in the first place, the iterator would start in ExportEntityConfigurable, which added price = 0 and then move on to ExportEntityChild which fixed the <price> node but added a separate attribute with the right value as in price = 75.

This will prevent the configurable to add a price if it's 0 and let the simple(s) decide on the actual price range.
