### ISSUE TITLE
MSI - Disabled stock source is exported to TW

### ISSUE THREAD

**Issue by RemcoWolterink** [EmicoEcommerce/Magento2TweakwiseExport#28]
Issue Brief
--
We currently have two stock sources in our website. Online and Store. The Store source is disabled and we would like that the products with > 0 qty to be exported to Tweakwise as these products are orderable in our physical store. 

As a result of this, we would like to sort the products based on the stock source and available qty (together with the regular sorting criteria). 

--
List the expected results as a bullet list of expectations
- [ ] Disabled store source can be exported to Tweakwise when there is qty available

**Comment by ahuininga-orisha** [comment]
@RemcoWolterink 

Why do you have the store source disabled? If the products are orderable in your physical store, wouldn't it be correct to have an enabled stock source as an pickup location? Or do you want to not be able to order the products at all on the website?

Logically it only seems correct that disabled stock sources aren't exported to TW.

**Comment by RemcoWolterink** [comment]
The stock in our store is not online orderable unless it is also in our webshop warehouse. But we would like to show the products in our webshop to let the customer go to the store. We do not have a pick-up functionality.

**Comment by ahuininga-orisha** [comment]
@jansentjeu What is your opinion on this?

I think it's correct that disabled stock locations don't get added to the stock count of an product.

**Comment by ahuininga-orisha** [comment]
@RemcoWolterink I've discussed this internally and we are not going to change this. It's correct that stock locations that are disabled are not counted towards the stock.

If you want to include the products in the stock count, the stock location should be enabled.

**Comment by RemcoWolterink** [comment]
Okay, I understand.
