### ISSUE TITLE
Logger fails with Psp/Log >= 2

### ISSUE THREAD

**Issue by evs-xsarus** [EmicoEcommerce/Magento2TweakwiseExport#64]
Issue Brief
--
Using newer versions of Magento, Psr/Log 2.x or 3.x is installed. That version has an update interface.

Environment
--
- [ ] PHP Version: 8.3
- [ ] Magento Version: 2.4.7
- [ ] Magento Enterprise: no
- [ ] Tweakwise Export Version: 7.0.1
- [ ] Magento Deploy Mode: production
- [ ] Third party modules: n/a

When running the export or `setup:di:compile` you get errors :+1: 
> Fatal error: Declaration of Tweakwise\Magento2TweakwiseExport\Model\Logger::emergency($message, array $context = []) must be compatible with Psr\Log\LoggerInterface::emergency(Stringable|string $message, array $context = []): void in /sites/tsf_upgrade/current/magento/vendor/tweakwise/magento2-tweakwise-export/Model/Logger.php on line 47

Fixable with

```
--- a/vendor/tweakwise/magento2-tweakwise-export/Model/Logger.php
+++ b/vendor/tweakwise/magento2-tweakwise-export/Model/Logger.php
@@ -44,7 +44,7 @@
     /**
      * {@inheritdoc}
      */
-    public function emergency($message, array $context = []): void
+    public function emergency(string|\Stringable $message, array $context = []): void
     {
         $this->log->emergency('[TweakWise] ' . $message, $context);
     }
@@ -52,7 +52,7 @@
     /**
      * {@inheritdoc}
      */
-    public function alert($message, array $context = []): void
+    public function alert(string|\Stringable $message, array $context = []): void
     {
         $this->log->alert('[TweakWise] ' . $message, $context);
     }
@@ -60,7 +60,7 @@
     /**
      * {@inheritdoc}
      */
-    public function critical($message, array $context = []): void
+    public function critical(string|\Stringable $message, array $context = []): void
     {
         $this->log->critical('[TweakWise] ' . $message, $context);
     }
@@ -68,7 +68,7 @@
     /**
      * {@inheritdoc}
      */
-    public function error($message, array $context = []): void
+    public function error(string|\Stringable $message, array $context = []): void
     {
         $this->log->error('[TweakWise] ' . $message, $context);
     }
@@ -76,7 +76,7 @@
     /**
      * {@inheritdoc}
      */
-    public function warning($message, array $context = []): void
+    public function warning(string|\Stringable $message, array $context = []): void
     {
         $this->log->warning('[TweakWise] ' . $message, $context);
     }
@@ -84,7 +84,7 @@
     /**
      * {@inheritdoc}
      */
-    public function notice($message, array $context = []): void
+    public function notice(string|\Stringable $message, array $context = []): void
     {
         $this->log->notice('[TweakWise] ' . $message, $context);
     }
@@ -92,7 +92,7 @@
     /**
      * {@inheritdoc}
      */
-    public function info($message, array $context = []): void
+    public function info(string|\Stringable $message, array $context = []): void
     {
         $this->log->info('[TweakWise] ' . $message, $context);
     }
@@ -100,7 +100,7 @@
     /**
      * {@inheritdoc}
      */
-    public function debug($message, array $context = []): void
+    public function debug(string|\Stringable $message, array $context = []): void
     {
         if ($this->enableDebugLog) {
             $this->log->debug('[TweakWise] ' . $message, $context);
@@ -110,7 +110,7 @@
     /**
      * {@inheritdoc}
      */
-    public function log($level, $message, array $context = []): void
+    public function log($level, string|\Stringable $message, array $context = []): void
     {
         $this->log->log($level, '[TweakWise] ' . $message, $context);
     }
```

Perhaps set the minimal Psr/Log to 2.0 and apply this patch.

**Comment by ahuininga-orisha** [comment]
@evs-xsarus Which version of the psr/log module do you have? I've have installed version 3.0.0 locally and don't have any problems.

**Comment by evs-xsarus** [comment]
@ah-net sorry, the error occured when running `setup:upgrade`, but I can't reproduce it anymore. Even when not having the patch installed.

I have psr/log 3.0.0 installed.

**Comment by ahuininga-orisha** [comment]
@evs-xsarus Is it possible that you ran the command with version 7.0.0 still installed? Because it looks like that from the error message. Because the : void is missing that is added in version 7.0.1 and was just released.

Fatal error: Declaration of Tweakwise\Magento2TweakwiseExport\Model\Logger::emergency($message, array $context = []) <----HERE  must be compatible with Psr\Log\LoggerInterface::emergency(Stringable|string $message, array $context = []): void in /sites/tsf_upgrade/current/magento/vendor/tweakwise/magento2-tweakwise-export/Model/Logger.php on line 47

**Comment by evs-xsarus** [comment]
That must be it, the patch isn't needed then. Thanks for looking into it.
