### ISSUE TITLE
Possible regression introduced.

### ISSUE THREAD

**Issue by igorwulff** [EmicoEcommerce/Magento2TweakwiseExport#70]
https://github.com/EmicoEcommerce/Magento2TweakwiseExport/blob/789aecd66ba5d68cf2dd32000b733a0bf66888dd/Model/Write/Products.php#L139-L141

I don't think this part of the code is correct and was unintentionally added in a recent PR. Its now doing a flush every second iteration, but also break somehow? Is this code that was used for testing purposes?

**Comment by ahuininga-orisha** [comment]
@igorwulff You are correct. This was changed during testing. I'll fix this

**Comment by ahuininga-orisha** [comment]
@igorwulff It seems that commit never made it in the master branch. And it was only wrong in that branch. But that it was changed before merging.

See https://github.com/EmicoEcommerce/Magento2TweakwiseExport/pull/39/commits/491e3b654a1fd30e01e524303fd47e3a03099dfc

**Comment by igorwulff** [comment]
My mistake then :D Thanks for looking into this.
